// dict_physical_and_mental_suffering.js —— 身心折磨篇词典（不含数字、标点、中文）

const DICT = {
  "the": { "ph": "/ðə/", "zh": "定冠词", },
  "ninth": { "ph": "/naɪnθ/", "zh": "第九", },
  "publication": { "ph": "/ˌpʌblɪˈkeɪʃn/", "zh": "出版物；发布", },
  "writer": { "ph": "/ˈraɪtər/", "zh": "作者", },
  "physical": { "ph": "/ˈfɪzɪkl/", "zh": "身体的", },
  "and": { "ph": "/ənd/", "zh": "和", },
  "mental": { "ph": "/ˈmentl/", "zh": "精神的；心理的", },
  "suffering": { "ph": "/ˈsʌfərɪŋ/", "zh": "痛苦；折磨", },
  "on": { "ph": "/ɑːn/", "zh": "在...之时", },
  "afternoon": { "ph": "/ˌæftərˈnuːn/", "zh": "下午", },
  "of": { "ph": "/əv/", "zh": "的", },
  "may": { "ph": "/meɪ/", "zh": "五月", },
  "our": { "ph": "/aʊr/", "zh": "我们的", },
  "pe": { "ph": "/ˌpiː ˈiː/", "zh": "体育（Physical Education）", },
  "teacher": { "ph": "/ˈtiːtʃər/", "zh": "老师", },
  "mr": { "ph": "/ˈmɪstər/", "zh": "先生", },
  "zhang": { "ph": "/ʒɑːŋ/", "zh": "张", },
  "let": { "ph": "/let/", "zh": "让；允许", },
  "us": { "ph": "/ʌs/", "zh": "我们（宾格）", },
  "run": { "ph": "/rʌn/", "zh": "跑步", },
  "times": { "ph": "/taɪmz/", "zh": "次数；倍", },
  "meters": { "ph": "/ˈmiːtərz/", "zh": "米（复数）", },
  "many": { "ph": "/ˈmeni/", "zh": "许多", },
  "students": { "ph": "/ˈstuːdnts/", "zh": "学生（复数）", },
  "suffered": { "ph": "/ˈsʌfərd/", "zh": "遭受（suffer过去式）", },
  "from": { "ph": "/frʌm/", "zh": "从；因", },
  "sore": { "ph": "/sɔːr/", "zh": "酸痛的", },
  "waist": { "ph": "/weɪst/", "zh": "腰部", },
  "back": { "ph": "/bæk/", "zh": "背部", },
  "even": { "ph": "/ˈiːvn/", "zh": "甚至", },
  "someone": { "ph": "/ˈsʌmwʌn/", "zh": "某人", },
  "threw": { "ph": "/θruː/", "zh": "扔；呕吐（throw/throw up过去式）", },
  "up": { "ph": "/ʌp/", "zh": "向上；呕吐", },
  "everywhere": { "ph": "/ˈevriwer/", "zh": "到处", },
  "we": { "ph": "/wiː/", "zh": "我们", },
  "had": { "ph": "/hæd/", "zh": "已经；有（have过去式）", },
  "then": { "ph": "/ðen/", "zh": "然后", },
  "group": { "ph": "/ɡruːp/", "zh": "团体；组", },
  "running": { "ph": "/ˈrʌnɪŋ/", "zh": "奔跑；跑步", },
  "followed": { "ph": "/ˈfɑːloʊd/", "zh": "跟随（follow过去式）", },
  "soon": { "ph": "/suːn/", "zh": "不久", },
  "after": { "ph": "/ˈæftər/", "zh": "在...之后", },
  "however": { "ph": "/haʊˈevər/", "zh": "然而", },
  "by": { "ph": "/baɪ/", "zh": "由于；通过", },
  "reason": { "ph": "/ˈriːzn/", "zh": "原因", },
  "fierce": { "ph": "/fɪrs/", "zh": "剧烈的；凶猛的", },
  "exercise": { "ph": "/ˈeksərsaɪz/", "zh": "锻炼；练习", },
  "before": { "ph": "/bɪˈfɔːr/", "zh": "在...之前", },
  "in": { "ph": "/ɪn/", "zh": "在...里面", },
  "class": { "ph": "/klæs/", "zh": "班级", },
  "two": { "ph": "/tuː/", "zh": "二", },
  "two": { "ph": "/tuː/", "zh": "二", },
  "three": { "ph": "/θriː/", "zh": "三", },
  "fell": { "ph": "/fel/", "zh": "掉落；跌倒（fall过去式）", },
  "behind": { "ph": "/bɪˈhaɪnd/", "zh": "落后；在后面", },
  "during": { "ph": "/ˈdʊrɪŋ/", "zh": "在...期间", },
  "that": { "ph": "/ðæt/", "zh": "那；那个", },
  "caused": { "ph": "/kɔːzd/", "zh": "引起（cause过去式）", },
  "school": { "ph": "/skuːl/", "zh": "学校", },
  "leaders": { "ph": "/ˈliːdərz/", "zh": "领导们（复数）", },
  "displeasure": { "ph": "/dɪsˈpleʒər/", "zh": "不悦；不满", },
  "they": { "ph": "/ðeɪ/", "zh": "他们", },
  "all": { "ph": "/ɔːl/", "zh": "所有的", },
  "classes": { "ph": "/ˈklæsɪz/", "zh": "班级（复数）", },
  "grade": { "ph": "/ɡreɪd/", "zh": "年级", },
  "stood": { "ph": "/stʊd/", "zh": "站立（stand过去式）", },
  "as": { "ph": "/æz/", "zh": "作为；像", },
  "punishment": { "ph": "/ˈpʌnɪʃmənt/", "zh": "惩罚", },
  "playground": { "ph": "/ˈpleɪɡraʊnd/", "zh": "操场", },
  "even": { "ph": "/ˈiːvn/", "zh": "甚至", },
  "teachers": { "ph": "/ˈtiːtʃərz/", "zh": "老师们（复数）", },
  "to": { "ph": "/tuː/", "zh": "到；向", },
  "platform": { "ph": "/ˈplætfɔːrm/", "zh": "平台；主席台", },
  "scolded": { "ph": "/ˈskoʊldɪd/", "zh": "责骂（scold过去式）", },
  "them": { "ph": "/ðem/", "zh": "他们（宾格）", },
  "seriously": { "ph": "/ˈsɪriəsli/", "zh": "严肃地；严重地", },
  "it": { "ph": "/ɪt/", "zh": "它", },
  "continued": { "ph": "/kənˈtɪnjuːd/", "zh": "持续（continue过去式）", },
  "for": { "ph": "/fɔːr/", "zh": "长达；为了", },
  "nearly": { "ph": "/ˈnɪrli/", "zh": "将近；几乎", },
  "minutes": { "ph": "/ˈmɪnɪts/", "zh": "分钟（复数）", },
  "was": { "ph": "/wʌz/", "zh": "是（is/am过去式）", },
  "publicly": { "ph": "/ˈpʌblɪkli/", "zh": "公开地", },
  "this": { "ph": "/ðɪs/", "zh": "这", },
  "painful": { "ph": "/ˈpeɪnfl/", "zh": "痛苦的", },
  "lesson": { "ph": "/ˈlesn/", "zh": "教训；课", },
  "result": { "ph": "/rɪˈzʌlt/", "zh": "结果", },
  "just": { "ph": "/dʒʌst/", "zh": "正如；仅仅", },
  "mentioned": { "ph": "/ˈmenʃnd/", "zh": "提到（mention过去式）", },
  "parent": { "ph": "/ˈperənt/", "zh": "家长", },
  "meeting": { "ph": "/ˈmiːtɪŋ/", "zh": "会议", },
  "health": { "ph": "/helθ/", "zh": "健康", },
  "is": { "ph": "/ɪz/", "zh": "是", },
  "especially": { "ph": "/ɪˈspeʃəli/", "zh": "尤其", },
  "important": { "ph": "/ɪmˈpɔːrtnt/", "zh": "重要的", },
  "end": { "ph": "/end/", "zh": "结束", },
  "please": { "ph": "/pliːz/", "zh": "请", },
  "stay": { "ph": "/steɪ/", "zh": "保持；停留", },
  "tuned": { "ph": "/tuːnd/", "zh": "调谐的；关注的", }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = DICT;
}