// dict_7113084e.js - 周报词典数据
// 关联文件: Week10.html
// 生成时间: 2026/5/10 18:16:16

// dict_liar_publication.js —— 第十篇：说谎者（The Tenth Publication）词典

const DICT = {
  "the": { "ph": "/ðə/", "zh": "定冠词" },
  "tenth": { "ph": "/tenθ/", "zh": "第十" },
  "publication": { "ph": "/ˌpʌblɪˈkeɪʃn/", "zh": "出版物；发布" },
  "writer": { "ph": "/ˈraɪtər/", "zh": "作者" },
  "helper": { "ph": "/ˈhelpər/", "zh": "助手" },
  "liar": { "ph": "/ˈlaɪər/", "zh": "说谎者" },
  "this": { "ph": "/ðɪs/", "zh": "这" },
  "is": { "ph": "/ɪz/", "zh": "是" },
  "a": { "ph": "/ə/", "zh": "一个（不定冠词）" },
  "complete": { "ph": "/kəmˈpliːt/", "zh": "完全的；彻底的" },
  "lie": { "ph": "/laɪ/", "zh": "谎言" },
  "before": { "ph": "/bɪˈfɔːr/", "zh": "在...之前" },
  "mid": { "ph": "/mɪd/", "zh": "中间的" },
  "term": { "ph": "/tɜːrm/", "zh": "学期；术语" },
  "exam": { "ph": "/ɪɡˈzæm/", "zh": "考试（examination缩写）" },
  "our": { "ph": "/aʊr/", "zh": "我们的" },
  "class": { "ph": "/klæs/", "zh": "班级" },
  "teacher": { "ph": "/ˈtiːtʃər/", "zh": "老师" },
  "told": { "ph": "/toʊld/", "zh": "告诉（tell过去式）" },
  "us": { "ph": "/ʌs/", "zh": "我们（宾格）" },
  "seats": { "ph": "/siːts/", "zh": "座位（复数）" },
  "will": { "ph": "/wɪl/", "zh": "将要" },
  "be": { "ph": "/biː/", "zh": "是；被" },
  "arranged": { "ph": "/əˈreɪndʒd/", "zh": "安排（arrange过去分词）" },
  "according": { "ph": "/əˈkɔːrdɪŋ/", "zh": "根据" },
  "to": { "ph": "/tuː/", "zh": "到；向" },
  "grades": { "ph": "/ɡreɪdz/", "zh": "成绩；年级（复数）" },
  "after": { "ph": "/ˈæftər/", "zh": "在...之后" },
  "new": { "ph": "/nuː/", "zh": "新的" },
  "spread": { "ph": "/spred/", "zh": "传播；蔓延" },
  "went": { "ph": "/went/", "zh": "变得；去（go过去式）" },
  "crazy": { "ph": "/ˈkreɪzi/", "zh": "疯狂的" },
  "and": { "ph": "/ənd/", "zh": "和" },
  "they": { "ph": "/ðeɪ/", "zh": "他们" },
  "even": { "ph": "/ˈiːvn/", "zh": "甚至" },
  "reserved": { "ph": "/rɪˈzɜːrvd/", "zh": "预订；保留（reserve过去式）" },
  "all": { "ph": "/ɔːl/", "zh": "所有的" },
  "whats": { "ph": "/wʌts/", "zh": "什么是（what is/was的缩写）" }, // 原文中为"What's"
  "more": { "ph": "/mɔːr/", "zh": "更多" },
  "thanks": { "ph": "/θæŋks/", "zh": "多亏；谢谢" },
  "news": { "ph": "/nuːz/", "zh": "消息（不可数）" },
  "many": { "ph": "/ˈmeni/", "zh": "许多" },
  "students": { "ph": "/ˈstuːdnts/", "zh": "学生（复数）" },
  "studied": { "ph": "/ˈstʌdid/", "zh": "学习（study过去式）" },
  "hard": { "ph": "/hɑːrd/", "zh": "努力地" },
  "got": { "ph": "/ɡɑːt/", "zh": "得到（get过去式）" },
  "satisfactory": { "ph": "/ˌsætɪsˈfæktəri/", "zh": "令人满意的" },
  "however": { "ph": "/haʊˈevər/", "zh": "然而" },
  "whether": { "ph": "/ˈweðər/", "zh": "是否" },
  "because": { "ph": "/bɪˈkɔːz/", "zh": "因为" },
  "were": { "ph": "/wɜːr/", "zh": "是（are过去式）" },
  "too": { "ph": "/tuː/", "zh": "太；也" },
  "excited": { "ph": "/ɪkˈsaɪtɪd/", "zh": "兴奋的" },
  "or": { "ph": "/ɔːr/", "zh": "或者" },
  "simply": { "ph": "/ˈsɪmpli/", "zh": "仅仅；简直" },
  "in": { "ph": "/ɪn/", "zh": "在...里面" },
  "maths": { "ph": "/mæθs/", "zh": "数学" },
  "lesson": { "ph": "/ˈlesn/", "zh": "课" },
  "its": { "ph": "/ɪts/", "zh": "它不是；它的" }, // 原文"It's" -> It is
  "not": { "ph": "/nɑːt/", "zh": "不" },
  "up": { "ph": "/ʌp/", "zh": "由...决定（固定搭配 up to）" },
  "choose": { "ph": "/tʃuːz/", "zh": "选择" },
  "your": { "ph": "/jɔːr/", "zh": "你的；你们的" },
  "them": { "ph": "/ðem/", "zh": "它们；他们（宾格）" },
  "will": { "ph": "/wɪl/", "zh": "将会" },
  "uniformly": { "ph": "/ˈjuːnɪfɔːrmli/", "zh": "统一地；一致地" },
  "his": { "ph": "/hɪz/", "zh": "他的" },
  "words": { "ph": "/wɜːrdz/", "zh": "话语（复数）" },
  "made": { "ph": "/meɪd/", "zh": "使得（make过去式）" },
  "feel": { "ph": "/fiːl/", "zh": "感觉" },
  "unsatisfactory": { "ph": "/ˌʌnsætɪsˈfæktəri/", "zh": "不令人满意的" },
  "although": { "ph": "/ɔːlˈðoʊ/", "zh": "虽然" },
  "action": { "ph": "/ˈækʃn/", "zh": "行动" },
  "encouraged": { "ph": "/ɪnˈkɜːrɪdʒd/", "zh": "鼓励（encourage过去式）" },
  "breaking": { "ph": "/ˈbreɪkɪŋ/", "zh": "打破（break动名词）" },
  "promises": { "ph": "/ˈprɑːmɪsɪz/", "zh": "承诺（复数）" },
  "hurt": { "ph": "/hɜːrt/", "zh": "伤害（过去式与原形同形）" },
  "enthusiasm": { "ph": "/ɪnˈθuːziæzəm/", "zh": "热情" },
  "trust": { "ph": "/trʌst/", "zh": "信任" },
  "but": { "ph": "/bʌt/", "zh": "但是" },
  "newest": { "ph": "/ˈnuːɪst/", "zh": "最新的" },
  "each": { "ph": "/iːtʃ/", "zh": "每个" },
  "group": { "ph": "/ɡruːp/", "zh": "小组" },
  "leader": { "ph": "/ˈliːdər/", "zh": "组长；领导者" },
  "team": { "ph": "/tiːm/", "zh": "团队" },
  "members": { "ph": "/ˈmembərz/", "zh": "成员（复数）" },
  "rearranged": { "ph": "/ˌriːəˈreɪndʒd/", "zh": "重新安排" },
  "successfully": { "ph": "/səkˈsesfəli/", "zh": "成功地" },
  "it": { "ph": "/ɪt/", "zh": "它" },
  "quite": { "ph": "/kwaɪt/", "zh": "相当；很" },
  "different": { "ph": "/ˈdɪfrənt/", "zh": "不同的" },
  "from": { "ph": "/frʌm/", "zh": "从...；与..." },
  "we": { "ph": "/wiː/", "zh": "我们" },
  "thought": { "ph": "/θɔːt/", "zh": "认为；想法（think过去式/thought名词）" },
  "looking": { "ph": "/ˈlʊkɪŋ/", "zh": "看；考虑（look动名词）" },
  "on": { "ph": "/ɑːn/", "zh": "在...上" },
  "bright": { "ph": "/braɪt/", "zh": "明亮的；好的" },
  "side": { "ph": "/saɪd/", "zh": "方面；边" },
  "he": { "ph": "/hiː/", "zh": "他" },
  "did": { "ph": "/dɪd/", "zh": "做（do过去式）" },
  "at": { "ph": "/æt/", "zh": "在" },
  "least": { "ph": "/liːst/", "zh": "至少；最少的" },
  "end": { "ph": "/end/", "zh": "结束" },
  "please": { "ph": "/pliːz/", "zh": "请" },
  "stay": { "ph": "/steɪ/", "zh": "保持" },
  "tuned": { "ph": "/tuːnd/", "zh": "调谐的；关注的" }
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DICT;
}