// dict_da3178e7.js - 周报词典数据
// 关联文件: Week11.html
// 生成时间: 2026/5/10 18:40:12

// dict_miss_double_championships.js —— 第十一篇：无缘双冠（Miss the Double Championships）词典

const DICT = {
  "time": { "ph": "/taɪm/", "zh": "时间" },
  "may": { "ph": "/meɪ/", "zh": "五月" },
  "8th": { "ph": "/eɪtθ/", "zh": "第八" },
  "2026": { "ph": "/ˈtwenti twenti sɪks/", "zh": "2026年" },
  "writer": { "ph": "/ˈraɪtər/", "zh": "作者" },
  "helper": { "ph": "/ˈhelpər/", "zh": "助手" },
  "miss": { "ph": "/mɪs/", "zh": "错过；想念" },
  "the": { "ph": "/ðə/", "zh": "定冠词" },
  "double": { "ph": "/ˈdʌbl/", "zh": "双倍的；双" },
  "championships": { "ph": "/ˈtʃæmpiənʃɪps/", "zh": "锦标赛；冠军头衔（复数）" },
  "when": { "ph": "/wen/", "zh": "当...时候" },
  "competition": { "ph": "/ˌkɑːmpəˈtɪʃn/", "zh": "比赛；竞争" },
  "reached": { "ph": "/riːtʃt/", "zh": "达到（reach过去式）" },
  "its": { "ph": "/ɪts/", "zh": "它的" },
  "climax": { "ph": "/ˈklaɪmæks/", "zh": "高潮" },
  "bit": { "ph": "/bɪt/", "zh": "一点" },
  "by": { "ph": "/baɪ/", "zh": "一点一点地（固定搭配 bit by bit）" },
  "class": { "ph": "/klæs/", "zh": "班级" },
  "two": { "ph": "/tuː/", "zh": "二" },
  "two": { "ph": "/tuː/", "zh": "二" },
  "three": { "ph": "/θriː/", "zh": "三" },
  "received": { "ph": "/rɪˈsiːvd/", "zh": "收到（receive过去式）" },
  "terrible": { "ph": "/ˈterəbl/", "zh": "糟糕的" },
  "news": { "ph": "/nuːz/", "zh": "消息" },
  "on": { "ph": "/ɑːn/", "zh": "在...之时" },
  "afternoon": { "ph": "/ˌæftərˈnuːn/", "zh": "下午" },
  "of": { "ph": "/əv/", "zh": "的" },
  "boys": { "ph": "/bɔɪz/", "zh": "男孩们（复数）" },
  "football": { "ph": "/ˈfʊtbɔːl/", "zh": "足球" },
  "team": { "ph": "/tiːm/", "zh": "队；团队" },
  "lost": { "ph": "/lɔːst/", "zh": "输；丢失（lose过去式）" },
  "to": { "ph": "/tuː/", "zh": "给；向；输给" },
  "one": { "ph": "/wʌn/", "zh": "一" },
  "zero": { "ph": "/ˈzɪroʊ/", "zh": "零" },
  "semi": { "ph": "/ˈsemi/", "zh": "半；部分" },
  "final": { "ph": "/ˈfaɪnl/", "zh": "决赛；最终的" },
  "this": { "ph": "/ðɪs/", "zh": "这" },
  "broke": { "ph": "/broʊk/", "zh": "打破（break过去式）" },
  "dream": { "ph": "/driːm/", "zh": "梦想" },
  "defending": { "ph": "/dɪˈfendɪŋ/", "zh": "卫冕；防守（defend动名词）" },
  "for": { "ph": "/fɔːr/", "zh": "长达；为了" },
  "four": { "ph": "/fɔːr/", "zh": "四" },
  "straight": { "ph": "/streɪt/", "zh": "连续的；直的" },
  "competitions": { "ph": "/ˌkɑːmpəˈtɪʃnz/", "zh": "比赛（复数）" },
  "and": { "ph": "/ənd/", "zh": "并且" },
  "warned": { "ph": "/wɔːrnd/", "zh": "警告（warn过去式）" },
  "all": { "ph": "/ɔːl/", "zh": "所有" },
  "students": { "ph": "/ˈstuːdnts/", "zh": "学生（复数）" },
  "never": { "ph": "/ˈnevər/", "zh": "从不" },
  "slack": { "ph": "/slæk/", "zh": "松懈；松弛" },
  "according": { "ph": "/əˈkɔːrdɪŋ/", "zh": "根据" },
  "newest": { "ph": "/ˈnuːɪst/", "zh": "最新的" },
  "may": { "ph": "/meɪ/", "zh": "五月" },
  "9th": { "ph": "/naɪnθ/", "zh": "第九" },
  "girls": { "ph": "/ɡɜːrlz/", "zh": "女孩们（复数）" },
  "got": { "ph": "/ɡɑːt/", "zh": "获得（get过去式）" },
  "championship": { "ph": "/ˈtʃæmpiənʃɪp/", "zh": "冠军；锦标赛" },
  "lets": { "ph": "/lets/", "zh": "让我们（let us的缩写）" },
  "congratulate": { "ph": "/kənˈɡrætʃuleɪt/", "zh": "祝贺" },
  "end": { "ph": "/end/", "zh": "结束" },
  "please": { "ph": "/pliːz/", "zh": "请" },
  "stay": { "ph": "/steɪ/", "zh": "保持" },
  "tuned": { "ph": "/tuːnd/", "zh": "关注的；调谐的" }
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DICT;
}